language: ruby

addons:
  code_climate:
    repo_token:
      secure: "gTQFE2IKJWLeR3HnlX0Z+BxlanO4iG/JqErdwCWZHLiI36MIea7QFG9FOXRZuaFR7x7PMbEVGk4EH4kXVNyNRPlR7yJPbtMPcjTr/zk/qtzDcUBAN58hXE0eBK49Ojgw+eA7cBcOt7gXZ9C/f6J4TaXgTQ5hSdhreloGevjq4qouMslRflh3nGA/lZjNTKg8unEwSbPm7TuxYfAkouZg/HVjr1VDVj4Q+VVglpiOpyOch5FTpbVlKCcV8lxD655Pod+yBC99GfaAFxXFYs7Ofxt9NsDEkh+qrm2CTiHyIodkPcYbFzp/Yvh+t3N1epLmnS+EhupzFAtBPePzN09loTCx2bUtphHEa7m4c8Qt+ap+fWdU0MKf/xstCwFYbqEiPSJzJh+0jDxj0fDOYfTCQrNW0Z1mwpNe7TK4tc6djwNAe39dYBH6kSsa9bTdGgNg0Ig/owtn4qTq7WdF/t2YTS07n7SEe32x2wHUGIm/zmTeZ5SaakeiETImLhyBKJqgPYJZI4S39FzNqL4a5D5vuxnvSpHKTlhk1yX0gTg4CY3ZWT5jLbxosPA8EM7+/EDjlwDZZEXMsuO41Fv9oFn9mTdkOSHMwoCe500bOZ1It4FL9WnaUGiLuJ4d/kI1W8MbxjR7V2b/1I8GSCI7dDTrRsNyMJYU4VCqrjjJkElvQCk="
